version: "3.1"

services:
  wordpress:
    image: wordpress
    ports:
      - 8321:80
    environment:
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DEBUG: 1
      ABSPATH: /usr/src/wordpress/
    volumes:
      - wordpress:/var/www/html
      - ./blocks:/var/www/html/wp-content/plugins/good-apollo
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress_test
  composer:
    image: composer
    volumes:
      - .:/app

volumes:
  testsuite:
  wordpress:
